services:
  sse-server:
    build:
      context: . # Use the Dockerfile in the current directory
      dockerfile: Dockerfile
    container_name: sse-server-no-agent
    ports:
      - "8888:8888"
    volumes:
      - ${PWD}:/app/app
    env_file:
      - .env
    entrypoint: ["uv","run","sse_server_research_agent.py","--transport", "sse", "--port", "8888"]
    tty: True

  sse-client:
    build: .
    volumes:
      - ${PWD}:/app/app
    tty: True
    # depends_on:
    #   sse-server-py:
    #     condition: service_healthy
    env_file:
      - .env
    entrypoint: ["python"]
    command: ["sse_client.py"]

  streamlit_app: # Name of the service
    build:
      context: . # Use the Dockerfile in the current directory
      dockerfile: Dockerfile-st
    container_name: pydantic_ai_demo_app # Optional: specific container name
    ports:
      - "8501:8501" # Map host port 8501 to container port 8501
    env_file:
      - .env # Load environment variables from the .env file
    volumes:
      - .:/app
    tty: True
    environment:
      - STREAMLIT_SERVER_PORT=8501

