services:
  train_custom:
    build: .
    platform: linux/arm64
    volumes:
      - ./:/app
      - ./output_model:/app/output_model
      - ../step0_building_base_model/tiny_gpt2_model:/app/tiny_gpt2_model
    command: python train.py

  llm-ui:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
      - ../step0_building_base_model/tiny_gpt2_model:/app/tiny_gpt2_model
