services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./data:/app/data
    env_file:
      - .env
    command: ["streamlit", "run", "streamlit_app/app.py", "--server.port=8501", "--server.enableCORS=false"]
    environment:
      - PYTHONPATH=/app
