# step4_inference_finetuned/docker-compose.yml
# version: "3.8"
services:
  infer_finetuned:
    build: .
    platform: linux/arm64
    volumes:
      - ../step3_finetune_custom/output_finetuned/:/app/ft_model  # mount fine-tuned model
