
services:
  streamlit_app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
    env_file:
      - .env   

  app:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env  
    entrypoint: ["python"]
    command: ["command_line.py"]     
