version: "3.8"
services:
  app-st:
    build: .
    ports:
      - "8511:8501"
    volumes:
      - ${PWD}:/app
    env_file:
      - .env
    entrypoint: ["streamlit", "run", "--server.port=8501", "--server.address=0.0.0.0"]
    # command: ["app-st.py"]
    command: ["app-files.py"]
  app:
    build: .
    volumes:
      - ${PWD}:/app
    env_file:
      - .env
    entrypoint: ["python"]
    command: ["app.py"]
