# docker-compose.yml
version: '3.8' # Specify docker-compose version

services:
  streamlit_app: # Name of the service
    build:
      context: . # Use the Dockerfile in the current directory
      dockerfile: Dockerfile
    container_name: pydantic_ai_demo_app # Optional: specific container name
    ports:
      - "8501:8501" # Map host port 8501 to container port 8501
    env_file:
      - .env # Load environment variables from the .env file
    volumes:
      - .:/app
    environment:
      # You can add other environment variables here if needed
      - STREAMLIT_SERVER_PORT=8501
    # Optional: Add volumes for live code reloading during development
    # volumes:
    #   - ./app:/app/app
