# Streamlit Frontend
FROM python:3.11-slim

WORKDIR /app
COPY frontend.py /app/
# RUN pip install streamlit requests httpx
RUN pip install streamlit websockets

CMD ["streamlit", "run", "frontend.py", "--server.port=8501", "--server.address=0.0.0.0"]
