version: '3.8'

# services:
#   qdrant:
#     image: qdrant/qdrant
#     container_name: qdrant
#     ports:
#       - "6333:6333"
#       - "6334:6334"
#     volumes:
#       - qdrant_data:/qdrant/storage
#     networks:
#       - qdrant-network
services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    environment:
      - QDRANT__STORAGE__OPTIMIZERS__INDEXING_THRESHOLD=0 # Disable indexing until optimization
      - QDRANT__STORAGE__WAL__WAL_CAPACITY_MB=1024 # Increase WAL capacity
      - QDRANT__STORAGE__PERFORMANCE__HNSW_INDEX=false # Disable HNSW during initial upload
    volumes:
      - ./qdrant_data:/qdrant/storage
      - ./qdrant_storage:/qdrant/storage/alternative # Additional storage
      - ./qdrant.yml:/qdrant/config/config.yaml
    networks:
      - qdrant-network
    deploy:
      resources:
        limits:
          memory: 4G

  streamlit-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: streamlit-app
    ports:
      - "8501:8501"
    environment:
      - QDRANT_URL=http://qdrant:6333
    depends_on:
      - qdrant
    networks:
      - qdrant-network
    volumes:
      - ./app:/app

networks:
  qdrant-network:

# volumes:
#   qdrant_data:
