version: '3.8'

services:
  rhyme_app:
    build:
      context: .  # Build from the root directory using the Dockerfile there
    container_name: rhyme-app-stdio
    tty: True
    volumes:
      - .:/app
    restart: unless-stopped
    ports:
      - "8501:8501" # Expose Streamlit's port to the host
    env_file:
      - .env      # Load environment variables (like OPENAI_API_KEY) from .env file
    # No networks needed for internal communication
    # No depends_on needed
