
services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app/app
    env_file:
      - .env
    command: ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.enableCORS=false"]
