#version: '3.8'

services:
  step1:
    build: ./step1
    ports:
      - 3001:3000
  step2-backend:
    build: ./step2
    command: npm run backend
    ports:
      - 4000:4000
  step2-frontend:
    build: ./step2
    command: npm run dev
    ports:
      - 3002:3000
  step3-backend:
    build: ./step3
    command: npm run backend
    ports:
      - 5000:5000
  step3-frontend:
    build: ./step3
    command: npm run dev
    ports:
      - 3003:3000
  mongo:
    image: mongo:6
    ports:
      - 27017:27017
  step4-backend:
    build: ./step4
    command: npm run backend
    ports:
      - 6000:6000
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/notesdb
  step4-frontend:
    build: ./step4
    command: npm run dev
    ports:
      - 3004:3000
    depends_on:
      - step4-backend
  step5-backend:
    build: ./step5
    command: npm run backend
    ports:
      - 7000:7000
  step5-frontend:
    build: ./step5
    command: npm run dev
    ports:
      - 3005:3000
    depends_on:
      - step5-backend
