version: "3.8"
services:
  app:
    build: .
    ports:
      - "8511:8501"
    volumes:
      - ${PWD}:/app/app
    env_file:
      - .env
    entrypoint: ["python"]
    command: ["filesystem.py"]


  # app-1:
  #   build: .
  #   ports:
  #     - "8511:8501"
  #   volumes:
  #     - ${PWD}:/app/app
  #   env_file:
  #     - .env
  #   entrypoint: ["python"]
  #   command: ["ollama.py"]

